### ISSUE TITLE
Use certificate to connect to schema registry

### ISSUE THREAD

**Issue by seriouslag** [kafkajs/confluent-schema-registry#107]
My use case requires a certificate to be attached to the HTTP calls.

I am unsure of how to attach my cert to the underlying HTTP calls.

Thoughts on adding an option to pass in an HTTP/S agent to the SchemaRegistry class.

Example:
```typescript
const host = "hostUrl";
const agent = new https.Agent({
  pfx:  pfxCert,
  passphrase: passphrase,
});

const registry = new SchemaRegistry({ host, agent });
```

**Comment by seriouslag** [comment]
I can tap into mappersmith to configure a global agent, I believe this should be made easier/hidden from consumers of the library since mappersmith is an internal implementation detail.

For those interested in how I am using it:
```typescript
import { SchemaRegistry } from '@kafkajs/confluent-schema-registry';
import { configs } from 'mappersmith';

const agent = new https.Agent({
  pfx:  pfxCert,
  passphrase: passphrase,
});

// add https agent for schema registry
configs.gatewayConfigs.HTTP = {
  configure: () => ({
    agent,
  }),
};
const host = "hostUrl";
const registry = new SchemaRegistry({ host });
```

**Comment by Nevon** [comment]
I agree, and I like your idea of allowing the injection of an agent into the constructor. I don't think it should be too hard to do, if you wanna take a crack at a PR.

**Comment by seriouslag** [comment]
Created PR #108
