### ISSUE TITLE
`registry.decode()` Uses Wrong Default Message Type When Protobuf Type Definitions Are Nested

### ISSUE THREAD

**Issue by MikeDalby** [kafkajs/confluent-schema-registry#112]
### Background
Node Version: `10.16.0`
@kafkajs/confluent-schema-registry: `2.0.1`

### Expected Behavior
We have a number of Protobuf Schemas with nested message type definitions that look like this

```proto
syntax = "proto3";
package io.my.company.protobufs.outermessagetype;

message OuterMessageType {
  string data = 1;
  InnerMessageType1 inner_message_type_1 = 2;
  InnerMessageType2 inner_message_type_2 = 3;

  message InnerMessageType1 {
    string some_field = 1;
  }
  message InnerMessageType2 {
    string some_other_field = 1;
  }
}
```

We'd like to create a registry that works for _multiple types_, so we're not specifying a `messageName`:
```node
const registry = new SchemaRegistry(
    {
      host: some_host,
      auth: {
        username: some_user,
        password: some_pass
      }
    }
  );
  ```

According to https://kafkajs.github.io/confluent-schema-registry/docs/usage#protobuf-1
>**Protobuf**
The only available option is messageName, which is used to select which message in a schema containing multiple messages to use for encoding/decoding the payload. **If omitted, the first message type in the schema is used.**

I would expect the `decode` function in the following code to return the _entire_ OuterMessageType object because it's the first message type in the schema:
```node
registry.decode(message.value)
```

### Actual Behavior
The call to `registry.decode(message.value)` only returns the `InnerMessageType1` object.

### One man's theory
Assuming this isn't the intended behavior I have a theory on why this is happening:

The following code traverses down the Namespaces to find the first message type definition
https://github.com/kafkajs/confluent-schema-registry/blob/10d38ffe1a0b83bd6f182241b7e53b06e114bbea/src/ProtoSchema.ts#L18-L25

When it gets to the `OuterMessageType` definition `reflection` is both a `Type` object and a `Namespace` object so the check for `reflection instanceof Namespace` returns true and `OuterMessageType` is skipped.

This is because Type extends Namespace here:
https://github.com/protobufjs/protobuf.js/blob/af1b449602b360091e191a58abde2f246d8b0f1d/src/type.js#L4-L6

Thought it doesn't look like it does here:
https://github.com/protobufjs/protobuf.js/blob/95b56817ef6fb9bdcb14d956c159da49d0889bff/index.d.ts#L1508

Modifying this check to stop on `Type` objects causes the `decode()` function to give me the expected behavior:
```node
if (reflection instanceof Namespace && !(reflection instanceof Type) && reflection.nested)
```

**Comment by Nevon** [comment]
I should preface this by saying that I'm not an authority on this. I have never used Protobuf outside of just some toying around.

That said, your explanation is sound and I think you're reading the intention of the code right. Would you be willing to put up a PR changing this? I suppose this will be a major version bump, since potentially people could have encoded messages using one type, and now it will use a different type to try to decode those, assuming that you don't define a message name and you have nested message types.

**Comment by MikeDalby** [comment]
@Nevon Created https://github.com/kafkajs/confluent-schema-registry/pull/113 for consideration.

**Comment by MikeDalby** [comment]
@Nevon Is there anything I can do to help get a release published for this?

**Comment by Nevon** [comment]
I'm afraid not. I just have a lot going on right now, both professionally and personally, so I haven't had the time to take care of this yet. Sorry about that.
