### ISSUE TITLE
ResponseError: Confluent_Schema_Registry - Unrecognized field: schemaType with Avro

### ISSUE THREAD

**Issue by olivd44** [kafkajs/confluent-schema-registry#155]
HTTP POST Content to Schema Registry (Confluent 5.4.2) seems to be malformed with latest version (3.0.1)

Server is returning 422 Confluent_Schema_Registry - Unrecognized field: schemaType

 [kafkajs/producer] Confluent_Schema_Registry - Unrecognized field: schemaType { ResponseError: Confluent_Schema_Registry - Unrecognized field: schemaType
    at next.then.catch (/root/path/node_modules/@kafkajs/confluent-schema-registry/dist/api/middleware/errorMiddleware.js:16:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'ResponseError',
  status: 422,
  unauthorized: false,
  url:
   'post https://schema-registry-fqdn/subjects/test-nodejs/versions' }

JSON content posted to SR is constructed by confluent-schema-registry and is not shown, even with log level to DEBUG

schemaType is a supported attributed of POST to endpoint /subjects/my_subject/versions so probably content is malformed but I have no way to check what is posted with 

  const { id } = await registry.register({ type: SchemaType.AVRO, schema: JSON.stringify(schema) }, {subject: "test-nodejs"})

**Comment by WaleedAshraf** [comment]
+1

**Comment by Nevon** [comment]
Looks like the schema registry folks made a backwards incompatible API change without versioning the API. Lovely!  Our tests are running against schema registry `5.5.3` at the moment, and are registering schemas with all three schema types.

https://github.com/kafkajs/confluent-schema-registry/blob/72009d5accb645daada31306fba3df0dd3c05383/src/SchemaRegistry.newApi.spec.ts#L181

If I downgrade to Schema Registry 5.4.2 I get the same error you're mentioning.

I opened up #158 to hack around this backwards incompatible change they made. Same hack they did to their own client in confluentinc/schema-registry/1288.

**Comment by Nevon** [comment]
This is fixed in v3.1.0
