### ISSUE TITLE
Method to fetch latest schema id by subject

### ISSUE THREAD

**Issue by sidharthv96** [kafkajs/confluent-schema-registry#17]
I have both Java and JS services, and the Java service will always write first to a topic and hence will register the avro schema in the registry.
I just want to use the JS service to send another message to the same topic using the already registered schema. But there is no method to fetch the latest version of the schema by just providing the subject.

`SchemaRegistryAPIClient.Subject.latestVersion` is already defined in the library. There's just no way to access it  as the API is private.
If there is a function along with `getRegistryId(subject: string, version: number): Promise<number>;` which automatically get's latest registryID, that would be clean.
eg: `getLatestRegistryId(subject: string): Promise<number>;`
which internally calls `SchemaRegistryAPIClient.Subject.latestVersion` and then passes that to `getRegistryId`.

**Comment by sidharthv96** [comment]
@Durairaj thanks for that PR!
Solves the issue.
@tulios Eagerly waiting for the next Release.

**Comment by tulios** [comment]
@sidharthv96 sorry for the delay, I will make the release.
