### ISSUE TITLE
 Converting byte[] to Kafka Connect data failed due to serialization error:  java.io.CharConversionException: Invalid UTF-32 character 0xed7a2268

### ISSUE THREAD

**Issue by sudheer9640** [kafkajs/confluent-schema-registry#182]
When json shema is used and http sink connector with json convertor is used, getting error as
 Converting byte[] to Kafka Connect data failed due to serialization error:  java.io.CharConversionException: Invalid UTF-32 character 0xed7a2268.
Json schema is as below
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "object",
      "properties": {
        "first": {
          "type": "string"
        },
        "last": {
          "type": "string"
        }
      }
    }
  }
}

Connector config was as below: 
{
    "name": "testconnector",
    "config": {
      "connector.class": "io.confluent.connect.http.HttpSinkConnector",
      "tasks.max": "1",
      "key.converter": "org.apache.kafka.connect.storage.StringConverter",
      "value.converter": "org.apache.kafka.connect.json.JsonConverter",
      "value.converter.schemas.enable": "false",
      "topics": "testtopic",
      "http.api.url": "https://postman.echo.com",
      "request.method": "post",
      "behavior.on.null.values": "ignore",
      "behavior.on.error": "log",
      "headers": "Content-Type:application/json|Accept:*/*",
      "max.retries": "5",
      "retry.backoff.ms": "3000",
      "retry.on.status.codes": "400-,500-",
      "request.body.format": "json",
      "report.errors.as": "error_string",
      "https.ssl.protocol": "TLSv1.2",
      "reporter.result.topic.replication.factor": "3",
      "reporter.error.topic.replication.factor": "3",
      "reporter.bootstrap.servers": "kafka:9071",
      "consumer.override.max.poll.interval.ms": "200000"
    }
  }

**Comment by Nevon** [comment]
I think you must be mistaking this project for https://github.com/apache/kafka. This is a library for using the Confluent Schema Registry from NodeJS applications.

**Comment by sudheer9640** [comment]
While producing kafka message, we are using encode method from kafkajs/confluent-schema-registry.
Iam passing Json schemaID and json payload as two params to this method.
In this method, payload is getting validated, converted to buffer and encoded with magic byte and some other encoding is happening. 
So in http sink connector, when JSON  value connector is used, iam facing this issue.
So do we need to encode when we use JSON schema as well
