### ISSUE TITLE
latest nodejs client gives 403 Forbidden on trying to get schema from registry

### ISSUE THREAD

**Issue by aonamrata** [kafkajs/confluent-schema-registry#193]
Hi,
I am using this client package to connect to an existing Schema Registry that we have.  I created a new schema via POST api and verified it with AKHQ. I am using `"@kafkajs/confluent-schema-registry": "^3.2.1"`

When i try to read that schema object in my code:
```
    let registry = null;
    registry = new SchemaRegistry({ host: 'https://dev-schema-registry.xxxx.io' });
    const result  = await registry.getLatestSchemaId('event.nr.fileIngestion-value');
    console.log('result==', result);
```

I get 403 Forbidden error
```
ResponseError: Confluent_Schema_Registry - Error, status 403: <html>
        <head><title>403 Forbidden</title></head>
        <body>
        <center><h1>403 Forbidden</h1></center>
        </body>
        </html>

            at D:\graphqlws\kafka-schema-registry-eg\node_modules\@kafkajs\confluent-schema-registry\dist\api\middleware\errorMiddleware.js:17:37
            at processTicksAndRejections (internal/process/task_queues.js:95:5) {
        status: 403,
        unauthorized: false,
        url: 'get https://dev-schema-registry.xxxx.io/subjects/event.nr.fileIngestion-value/versions/latest'
        }
```

Any other function also gives me same error.  When i try to connect to the same schema registry using python client, it works. You can refer to: https://github.com/aonamrata/schema-registry-eg for both the examples.

I also tried manually hitting `https://dev-schema-registry.xxxx.io/subjects/event.nr.fileIngestion-value/versions/latest` from browser and that works. It returns the json object. 

Can someone please help me identity the problem? There is no auth that i know of because i can hit the url directly. Only via the module it gives me error.

Thanks.

**Comment by Nevon** [comment]
What version of the schema registry are you using? This error is clearly coming from the server, so there must be some auth or restriction in place.

What happens if you just `curl -XGET https://dev-schema-registry.xxxx.io/subjects/event.nr.fileIngestion-value/versions/latest`?

**Comment by aonamrata** [comment]
> What version of the schema registry are you using?

I am not sure but let me ask around. But i know that we are using docker image with  `FROM confluentinc/cp-schema-registry:latest` . But let me check when it was last deployed.

 

> What happens if you just `curl -XGET https://dev-schema-registry.xxxx.io/subjects/event.nr.fileIngestion-value/versions/latest`?

Yea, this works. that is what is confusing. and its the same url even in the error message.
![image](https://user-images.githubusercontent.com/1792005/157409154-7e3f33fc-c91a-4589-9ac8-c4b436f92bac.png)

**Comment by Nevon** [comment]
Could you share the docker-compose file you're using locally? I'm having issues trying to upgrade from confluent platform 5 to 6.

**Comment by aonamrata** [comment]
> Could you share the docker-compose file you're using locally? I'm having issues trying to upgrade from confluent platform 5 to 6.

Hey @Nevon , Sorry for all the trouble. One of our devops engineer was help me out. It turned out that AWS WAF was blocking the requests with NoUserAgent HEADER from going to the server. That is why the url on its own worked but not from the module. 
On closing note, we are using schema registry version 7.0.0.

**Comment by Nevon** [comment]
That's an interesting observation though. I looked through both the Java and Python schema registry clients, and neither of them explicitly set a user-agent header, which probably means that they use whatever default user-agent header their respective HTTP libraries set. I can't tell with the Java client, but the Python client uses `requests`, which definitely does set a user-agent header by default. So to avoid this in the future, we should probably set a user agent as well. Opened up another issue for it #194
