### ISSUE TITLE
Apicurio registry compatibility with order of register() operations

### ISSUE THREAD

**Issue by evanshortiss** [kafkajs/confluent-schema-registry#200]
The current [procedure](https://github.com/kafkajs/confluent-schema-registry/blob/master/src/SchemaRegistry.ts#L125-L156) for registering a schema starts by trying to fetch and update the compatibility rules. This works fine with the Confluent registry, but caused an issue in my testing with Apicurio registry.

Understandably this could be considered an issue with the Apicurio API compatibility layer, but generally the order of operations is unusual. If the existing config is not found, a PUT is still attempted to modify a non-existing config.

A simple workaround was to switch the order of operations from:

1. `await this.api.Subject.config(args)`
1. `await this.api.Subject.updateConfig(args)`
1. `await this.api.Subject.register(args)`

To this (2 & 3 switched):

1. `await this.api.Subject.config(args)`
1. `await this.api.Subject.register(args)`
1. `await this.api.Subject.updateConfig(args)`

AFAICT this works as intended with both registry APIs. Does it make sense to make this change, or would it have unintended side effects?

**Comment by evanshortiss** [comment]
> caused an issue in my testing with Apicurio registry

Specifically, the `updateConfig` call fails with a 404 since the subject does not yet exist. The Confluent implementation seems to go ahead and create an empty/placeholder subject if one doesn't already exist, and therefore doesn't 404.

**Comment by Nevon** [comment]
I suppose in Confluent schema registry when doing `updateConfig` we're not dependent on the subject existing because we're not modifying the subject, we're modifying the config, which is why we're able to do that before the subject actually exists. In apicurio I suppose they require the subject to exist before being able to modify the configuration for a subject.

Either way, I think it seems like a reasonable change to make.

**Comment by evanshortiss** [comment]
Awesome. Thanks @Nevon. I draft up a PR soon.

**Comment by evanshortiss** [comment]
@Nevon closing this since you've merged the PR. Do you have a timeline for a new release?

**Comment by Nevon** [comment]
Most likely during the week starting May 2nd.

**Comment by evanshortiss** [comment]
Thank you for the confirmation.
