### ISSUE TITLE
support for open source schema registries like apicurio or karpace 

### ISSUE THREAD

**Issue by ivar891** [kafkajs/confluent-schema-registry#210]
does this support encoding and decoding with open source schema registries like apicurio or karpace  or any other open source repositories ?

**Comment by Nevon** [comment]
If those registries implement the confluent schema registry API, sure. I haven't tested it with either, but from a cursory look it looks like Karpace does implement the confluent schema registry API. Apicurio's documentation is incomprehensible to me, so I can't tell what the heck it actually does.

But in general, this library implements support for the confluent schema registry. These other registries _may_ implement the same API, in which case they will work with this library.
