### ISSUE TITLE
Move to 'avro-js' from 'avsc'

### ISSUE THREAD

**Issue by snird** [kafkajs/confluent-schema-registry#241]
`avsc`: https://www.npmjs.com/package/avsc
`avro-js`: https://www.npmjs.com/package/avro-js

`avsc` is lagging way behind in the protocol implementation. Its implementation is 1.8-ish compatible:
https://github.com/mtth/avsc/issues/238

And it isn't seem to be worked on anymore.

`avro-js` is the official implementation, and is fully compatible with the latest 1.11.1:
https://github.com/apache/avro/tree/master/lang/js

The API of the libraries is compatible.
I hot-switched for `avro-js` in this fork:
https://github.com/snird/confluent-schema-registry-avro-js
(not ready or aimed to be ready for merge)

It works as expected and working on production load at the moment.

I see no reason not to move to `avro-js` in this repo.

**Comment by potyl** [comment]
I see that this issue is closed but there doesn't seem a corresponding PR. Is `avro-js` going to be replacing `avsc`?

@snird the repo https://github.com/snird/confluent-schema-registry-avro-js is gone.

**Comment by snird** [comment]
Avro-js does not support BigInt or something like that for big numbers.
So even though they implemented a more recent spec, it is effectively unusable in a production environment.
That's why I deleted this
