### ISSUE TITLE
Support logical types

### ISSUE THREAD

**Issue by timkendall** [kafkajs/confluent-schema-registry#37]
The Avro specification and `avsc` implementation support defining [Logical Types](https://avro.apache.org/docs/1.8.2/spec.html#Logical+Types). In `avsc` this is done by specifying a value for the `logicalTypes` field in `avro.Type.forSchema/2`'s options argument. We should support this feature  as it is a common use-case for production applications.

For example:
```ts
const type = avro.Type.forSchema(schema, { logicalTypes: { decimal: DecimalType } })
```

**Comment by erikengervall** [comment]
Hey, thanks for your issue!

I'd love some help with this feature, feel free to open a PR and I'll assist best I can! 👍

**Comment by wfpena** [comment]
So this lib doesn't have any support for Date / Timestamp types? As it seems it doesn't support logicalTypes.

Because I'm trying to serialize a Date type and it always seems to give me error.

**Comment by cristianbriscaru** [comment]
For anyone facing this issue it looks like this library supports logical types but it's not documented anywhere : 

`
const avro = require('avsc');

class DateType extends avro.types.LogicalType {
  _fromValue(val) {
    return new Date(val);
  }
  _toValue(date) {
    return date instanceof Date ? +date : undefined;
  }
  _resolve(type) {
    if (avro.Type.isType(type, 'long', 'string', 'logical:timestamp-millis')) {
      return this._fromValue;
    }
  }
}
 const registry = new SchemaRegistry({ host: 'http://localhost:8081' }, { forSchemaOptions: { logicalTypes: { 'timestamp-millis':  DateType }}} )

const schema = {
    "namespace": 'com.grapedata.space.avro.resource',
    "name": 'companies',

    "type": 'record',
    "fields": [
        {
            name: 'id',
            type: 'int'
        }, 
        {
            name: 'name',
            type: 'string',
        },
        {
            "name": "createdDate",
            type: {type: 'long', logicalType: 'timestamp-millis'},
            "doc": "Date-time as the number of milliseconds since the epoch of 1970-01-01T00:00:00Z",
        }
    ]
}

const value = { id: 1, name: 'test-name', createdDate: new Date() }
const { id } = await registry.register(schema,{subject: 'test-topic-value'});
const encodedValue = await registry.encode(id, value);
 const decodedValue = await registry.decode(encodedValue)

`
