### ISSUE TITLE
Encode message with local avsc

### ISSUE THREAD

**Issue by shakegioh** [kafkajs/confluent-schema-registry#49]
Hi,

I'm learning kafka and schema registry, and according to documentation and the source code I'm not able to do something like this:

```javascript
const myAvroSchema = await readAVSCAsync('path/to/schema.avsc');
const message = registry.encode(myAvroSchema, payload);
```

Is that possible to do something like this? Even if it's not implemented yet, but if it's possible, I can try to contribute...

**Comment by Nevon** [comment]
`registry.encode` takes a schema id and the payload to encode. The schema id will be used to look up the schema from the schema registry, which is the point of this library.

If you just want to encode with a local schema, and not use a schema registry, you can just use `avsc` directly. If you're using the schema registry, you should instead upload your schema to the registry and use the schema id you get back to encode.

**Comment by shakegioh** [comment]
Thank you for your fast reply.

Fair enough... But how will I know the schema id as it may change?

1. Create some environment variables to set schema id or make it hard coded
2. Always execute a function that creates the schemas I need and get its ids on startup
3. Get schema id from the schema registry's API `GET /subjects/products-value/v1`

Which of these options are considered best practices?

If the option 3 is the best one, then could I contribute to it?

**Comment by Nevon** [comment]
The schema id won't change, so technically 1 would work, but personally I prefer option 2 or 3. I do 2 where possible, and if that's not an option, I go with 3. 

The library actually already supports getting a schema id by subject and version - it's just not documented. Check SchemaRegistry.ts. A contribution adding documentation on that would be great.
