### ISSUE TITLE
Error: potential precision loss

### ISSUE THREAD

**Issue by alonisser** [kafkajs/confluent-schema-registry#53]
Trying to debug an issue with decoding avro messges created by kafka connect debezium mongo

Not sure if the problem is here or in avsc directly
And getting this [stacktrace](https://gist.github.com/alonisser/6fe4fd9697b5c62f91b41230222027df#file-exception)
I've tried fetching the same messages with python confluent avro consumer and it does work as expected, also the key is serialized as expected, just the value ot
The schema (I've copied from debugging step by step through the code) is here and the actual buffer is [here](https://gist.github.com/alonisser/6fe4fd9697b5c62f91b41230222027df#file-buffer):

Any clues to what I'm missing here? Thanks..

**Comment by Nevon** [comment]
This is a duplicate of #24.

This is avsc protecting you from losing precision as you are trying to decode a Long value (int64) that does not fit into a javascript Number type. https://github.com/mtth/avsc/wiki/Advanced-usage#custom-long-types. Python has a Long integer type available, so there they simply deserialize large numbers to that, but in Javascript there wasn't a big enough integer type available until Node 12 (BigInt), so you need to provide your own Long type that avsc can use.

Currently this package doesn't expose the `avsc` module to its consumers, so I'm not sure if there is a way to set the custom implementation, as mentioned in #24. Perhaps @tulios can shed some light on how we did it in our services that needed Long support (I don't have access to those services anymore).

**Comment by alonisser** [comment]
As a work around, does it support just extracting the schema from the registry and then overriding it?

**Comment by alonisser** [comment]
I've found a workaround if someone bumps into this
I'm using the 'forSchemaOptions' you can pass when creating the SchemaRegistry and pass inside a typeHook and registry with the `long` type .

See [this issue](https://github.com/mtth/avsc/issues/294) in the underlying avsc library for the exact details on how I've solved this.

Perhaps would be helpful for someone in the future

**Comment by bacebu4** [comment]
Btw, this worked for me, though I haven't used `typeHook` 

```ts
const unsafeLongType = avro.types.LongType.__with({
      fromBuffer: (buf: Buffer) => Number(buf.readBigInt64LE()),
      toBuffer: (n: number) => {
        const buf = Buffer.alloc(8);
        buf.writeBigInt64LE(BigInt(n));
        return buf;
      },
      fromJSON: Number,
      toJSON: Number,
      isValid: (n: unknown) => typeof n === 'number',
      compare: (n1: number, n2: number) => {
        return n1 === n2 ? 0 : n1 < n2 ? -1 : 1;
      },
    });

    const registry = new SchemaRegistry(
      { host: config.kafka.schemaRegistryHost },
      {
        forSchemaOptions: {
          registry: { long: unsafeLongType },
        },
      },
    );
```

```
"@kafkajs/confluent-schema-registry": "3.3.0",
```
