### ISSUE TITLE
Support pre-registered schemas

### ISSUE THREAD

**Issue by jbooth-mastery** [kafkajs/confluent-schema-registry#56]
It'd be great to have support for the schema-check, rather than only schema-register functionality of getting an id for a given schema in the schema registry. From the [docs](https://docs.confluent.io/1.0/schema-registry/docs/intro.html):

```
# Check whether a schema has been registered under subject "Kafka-key"
$ curl -X POST -i -H "Content-Type: application/vnd.schemaregistry.v1+json" \
    --data '{"schema": "{\"type\": \"string\"}"}' \
    http://localhost:8081/subjects/Kafka-key
```

Rationale: We want to do the register outside of server invocation (eg, in the CI deployment, before the actual code deploy), so that if a developer is working with a local branch against a shared dev environment, they won't accidentally register a new schema by launching the server on a WIP branch.

**Comment by Nevon** [comment]
This actually exists, and just isn't documented:

https://github.com/kafkajs/confluent-schema-registry/blob/master/src/SchemaRegistry.ts#L135-L147

**Comment by jbooth-mastery** [comment]
Those fetch a schema given the id. The method I'm talking about above takes a schema and returns the id it is registered under, or an error code if it isn't registered.

It is just like the `POST /subjects/<subject>/versions`, except it won't actually register the schema with the schema registry.

**Comment by Nevon** [comment]
I see, that makes sense. You want to be able to get the registry id for a specific version of the subject, based on the schema, not get the registry id based on the subject + version.

**Comment by jbooth-mastery** [comment]
Yep! In an ideal world where you have only one producer on a topic, doing this is equivalent to the latest version. In a non-ideal world, where you might have a topic with multiple producers, someone has to upgrade first. The other producers will upgrade eventually, but need to pull the correct schema id for the schema they are holding in the meantime.

**Comment by Nevon** [comment]
This looks like a pretty straight forward feature to implement, if you want to give it a shot.

**Comment by Nevon** [comment]
@jbooth-mastery I created a PR with this added. Let me know if it was what you had in mind.

**Comment by jbooth-mastery** [comment]
LGTM! Better than I would have done too, I only dabble in typescript.
