### ISSUE TITLE
How to configure tls certificate for schema registry

### ISSUE THREAD

**Issue by mingliangguo** [kafkajs/confluent-schema-registry#61]
I am looking for an example of configuring tls certificate for schema registry server configured with self-signed certificate. I have searched the repo and also in internet, but didn't find anything helpuful. Can someone kindly let me know if it's supported at the time?

I looked at the code and it looks like SchemaRegistry utilize `mappersmith` to make http/https calls, however, it doesn't seem exposing the options of allowing ceritificate to be passed?
The following is the example I found in [mappersmith`'s npm website](https://www.npmjs.com/package/mappersmith):

```javascript
import fs from 'fs'
import https from 'https'
import { configs } from 'mappersmith'
 
const key = fs.readFileSync('/path/to/my-key.pem')
const cert =  fs.readFileSync('/path/to/my-cert.pem')
 
configs.gatewayConfigs.HTTP = {
  configure() {
    return {
      agent: new https.Agent({ key, cert })
    }
  }
}
```

Are there alternative ways to do this? Thanks for any feedback!

**Comment by mingliangguo** [comment]
Never mind, it looks like I can set the cert via `NODE_EXTRA_CA_CERTS`.

**Comment by mingliangguo** [comment]
@chase1745 for my case, I don't need the key to access the schema-registry. Are you still seeing issues even with the certs being set?

**Comment by chase1745** [comment]
Yeah, I need to specify both the CA cert as well as a key, and can't figure out how to specify the key. Any ideas?
