### ISSUE TITLE
Please release a new version.

### ISSUE THREAD

**Issue by seokgyo** [kafkajs/confluent-schema-registry#67]
Hi,
getRegistryIdBySchema() has not been released yet. Could you please release it?

**Comment by Nevon** [comment]
@erikengervall: Do you have it documented anywhere how to cut a release? Is it just:

* Update changelog
* `npm version major|minor|patch`
* `git push`

And then the normal PR flow and the pipeline makes the actual release?

**Comment by erikengervall** [comment]
> Do you have it documented anywhere how to cut a release?

No, we probably should.

> Update changelog
> npm version major|minor|patch
> git push

Here's an example of these steps https://github.com/kafkajs/confluent-schema-registry/commit/dea9d9d3b2ca90a9bebd771b97278c6cc7c02a2d

From what I recall the pipeline handles the final release steps once you push a new tag with the new version number.

**Comment by erikengervall** [comment]
1.0.6 released https://www.npmjs.com/package/@kafkajs/confluent-schema-registry/v/1.0.6
