### ISSUE TITLE
SSL and SASL plaintext

### ISSUE THREAD

**Issue by warrenfrost** [kafkajs/confluent-schema-registry#77]
Hi,

Our schema registry is secured with SSL and SASL plaintext. Is there any way to use this with Confluent Schema Registry? I don't seem to be able to find any examples.

Many thanks,

Warren

**Comment by Nevon** [comment]
Can you provide more context on how you are securing your registry? To my knowledge, the only authentication mechanism that is offered is basic auth: https://docs.confluent.io/current/security/basic-auth.html#schema-registry

**Comment by warrenfrost** [comment]
Hi Nevon. Since posting this issue I have been informed that our schema registry is indeed using basic authentication and not SASL as I was originally told.

Apologies for taking up your time. Please feel free to close this issue.

Warren
