### ISSUE TITLE
Feature References Request

### ISSUE THREAD

**Issue by smhmayboudi** [kafkajs/confluent-schema-registry#82]
Do you have any plan to support references?

Example:
```json
{
  "references": [
    {
      "name": "RtValidateReqDto",
      "subject": "fip.common.RtValidateReqDto",
      "version": 1
    },
    {
      "name": "RtResDto",
      "subject": "fip.common.RtResDto",
      "version": 1
    }
  ],
  "schema":"{\"namespace\":\"fip.common\",\"name\":\"RtValidateDto\",\"type\":\"record\",\"fields\":[{\"name\":\"err\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"req\",\"type\":[\"null\",\"RtValidateReqDto\"],\"default\":null},{\"name\":\"res\",\"type\":[\"null\",\"RtResDto\"],\"default\":null}]}",
  "schemaType":"AVRO"
}
```

**Comment by slominskir** [comment]
Another attempt at references:  https://github.com/kafkajs/confluent-schema-registry/pull/121

Can we get one of these merged?

**Comment by brinchj** [comment]
Hi Folks. I would love for this project to support Protocol Buffer references (imports). I have written up a PR that implements the first step of this support over in https://github.com/kafkajs/confluent-schema-registry/pull/135

I have just updated the description to explain the context, how it works, and what's still missing (as far as I know). I would greatly appreciate if one of you would take a look and tell me if it makes sense, or if there are parts that are not easy to follow 👍

**Comment by brinchj** [comment]
Perhaps we can team up and create a little task force for all of us who are interested in adding support for references :)
